{% set version = "4.0b8" %}
{% set git_rev = "e266c5c" %}

package:
  name: constructor
  version: {{ version }}

source:
  - git_url: https://github.com/jaimergp/constructor.git
    # see https://github.com/conda/constructor/pull/474
    # for commit hashes
    git_rev: {{ git_rev }}

build:
  number: 2
  string: "pyh{{ PKG_HASH }}_{{ git_rev }}_{{ PKG_BUILDNUM }}"
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - constructor = constructor.main:main
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - __{{ target_os }}
    - conda >=4.14
    - python >=3.7
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1  # [win or osx]
    - nsis >=3.08   # [win]

test:
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pillow >=3.1
    - pytest
  commands:
    - pytest -v tests
    - set "CONSTRUCTOR_SIGNTOOL_PATH=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool.exe"  # [win]
    - set "CONSTRUCTOR_SIGNING_CERTIFICATE=certificate.pfx"   # [win]
    - set "CONSTRUCTOR_PFX_CERTIFICATE_PASSWORD=1234"  # [win]
    - powershell scripts\create_self_signed_certificate.ps1  # [win]
    - copy /Y "%CONSTRUCTOR_SIGNING_CERTIFICATE%" examples\signing\certificate.pfx  # [win]
    # Skip for linux-aarch64 because examples use "main" channel which has no builds for that platform.
    - python scripts/run_examples.py  # [not aarch64]
    - constructor -V
  imports:
    - constructor

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
