{% set version = "4.0b10" %}
{% set git_rev = "1913d14" %}

package:
  name: constructor
  version: {{ version }}

source:
  git_url: https://github.com/jaimergp/constructor.git
  # see https://github.com/conda/constructor/pull/474
  # for commit hashes
  git_rev: {{ git_rev }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - constructor = constructor.main:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - __{{ target_os }}
    - conda >=4.6
    - python >=3.7
    - ruamel.yaml >=0.11.14,<0.18
    - conda-standalone
    - pillow >=3.1
    - nsis >=3.08      # [win]
  run_constrained:   # [unix]
    - nsis >=3.08      # [unix]

test:
  files:
    - test_win.bat
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pip
    - pytest
    - nsis * *log*  # [win]
  commands:
    - pip check
    - pytest -v tests
    # Skip for linux-aarch64 because examples use "main" channel which has no builds for that platform.
    - set "NSIS_USING_LOG_BUILD=1"  # [win]
    - python scripts/run_examples.py  # [unix and not aarch64]
    - test_win.bat  # [win]
    - constructor -V
  imports:
    - constructor

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - isuruf
    - jaimergp
    - jakirkham
    - jschueller
    - mbargull
    - msarahan